export const useNavigationLinks = defineStore("navLinks", () => {
  const links = ref([
    {
      id: 1,
      title: "Women",
      slug: "/women",
      links: [
        {
          id: 1,
          title: "Сумки",
          slug: "/bags",
          sublinks: [
            { id: 1, title: "Все сумки", slug: "/collection/teddy" },
            { id: 1, title: "Средние сумки", slug: "/collection/teddy" },
            { id: 1, title: "Мини-сумки", slug: "/collection/teddy" },
          ],
        },
        { id: 2, title: "Кошельки", slug: "/bags" },
        { id: 3, title: "Косметички", slug: "/bags" },
        { id: 4, title: "Рюкзаки", slug: "/bags" },
        { id: 5, title: "Аксессуары", slug: "/bags" },
        { id: 6, title: "Ремни", slug: "/bags" },
        { id: 7, title: "Духи", slug: "/bags" },
        { id: 8, title: "Для дома", slug: "/bags" },
      ],
      collections: [
        { id: 1, title: "Teddy", slug: "/collection/teddy" },
        { id: 2, title: "Key", slug: "/collection/teddy" },
        { id: 3, title: "Tie", slug: "/collection/teddy" },
        { id: 4, title: "Waves", slug: "/collection/teddy" },
        { id: 5, title: "Trio", slug: "/collection/teddy" },
        { id: 6, title: "Classic", slug: "/collection/teddy" },
        { id: 7, title: "Bubbles", slug: "/collection/teddy" },
        { id: 8, title: "Royal", slug: "/collection/teddy" },
        { id: 9, title: "Le Lin", slug: "/collection/teddy" },
        { id: 10, title: "Geometry", slug: "/collection/teddy" },
        { id: 11, title: "Texture", slug: "/collection/teddy" },
        { id: 12, title: "Venice", slug: "/collection/teddy" },
        { id: 13, title: "Fleur", slug: "/collection/teddy" },
        { id: 14, title: "Italy", slug: "/collection/teddy" },
      ],
    },
    {
      id: 2,
      title: "Men",
      slug: "/men",
      links: [
        { id: 1, title: "Сумки", slug: "/men/bags" },
        { id: 2, title: "Кошельки", slug: "/men/bags" },
        { id: 3, title: "Косметички", slug: "/men/bags" },
        { id: 4, title: "Рюкзаки", slug: "/men/bags" },
        { id: 5, title: "Аксессуары", slug: "/men/bags" },
        { id: 6, title: "Ремни", slug: "/men/bags" },
        { id: 7, title: "Духи", slug: "/men/bags" },
        { id: 8, title: "Для дома", slug: "/men/bags" },
      ],
      collections: [
        { id: 1, title: "Teddy", slug: "/collection/teddy" },
        { id: 2, title: "Key", slug: "/collection/teddy" },
        { id: 3, title: "Tie", slug: "/collection/teddy" },
        { id: 4, title: "Waves", slug: "/collection/teddy" },
        { id: 5, title: "Trio", slug: "/collection/teddy" },
        { id: 6, title: "Classic", slug: "/collection/teddy" },
        { id: 7, title: "Bubbles", slug: "/collection/teddy" },
        { id: 8, title: "Royal", slug: "/collection/teddy" },
        { id: 9, title: "Le Lin", slug: "/collection/teddy" },
        { id: 10, title: "Geometry", slug: "/collection/teddy" },
        { id: 11, title: "Texture", slug: "/collection/teddy" },
        { id: 12, title: "Venice", slug: "/collection/teddy" },
        { id: 13, title: "Fleur", slug: "/collection/teddy" },
        { id: 14, title: "Italy", slug: "/collection/teddy" },
      ],
    },
    {
      id: 3,
      title: "New",
      slug: "/",
    },
    {
      id: 4,
      title: "Gifts",
      slug: "/",
    },
    {
      id: 5,
      title: "Sale",
      slug: "/",
    },
  ]);

  return { links };
});
