export const useNavigationLinks = defineStore("navLinks", () => {
  const links = ref([
    {
      id: 1,
      title: "Women",
      slug: "/women",
      links: [
        {
          id: 1,
          title: "Сумки",
          slug: "sumki",
          is_active: 1,
          sale: null,
          sort: 1,
          created_at: "2024-06-01T17:39:52.000000Z",
        },
        {
          id: 2,
          title: "Рюкзаки",
          slug: "riukzaki",
          is_active: 1,
          sale: null,
          sort: 2,
          created_at: "2024-06-01T17:39:52.000000Z",
        },
        {
          id: 3,
          title: "Ремни",
          slug: "remni",
          is_active: 1,
          sale: null,
          sort: 3,
          created_at: "2024-06-01T17:39:52.000000Z",
        },
        {
          id: 4,
          title: "Кошельки",
          slug: "koselki",
          is_active: 1,
          sale: null,
          sort: 4,
          created_at: "2024-06-01T17:39:52.000000Z",
        },
        {
          id: 5,
          title: "Косметички",
          slug: "kosmeticki",
          is_active: 1,
          sale: null,
          sort: 5,
          created_at: "2024-06-01T17:39:52.000000Z",
        },
        {
          id: 6,
          title: "Для дома",
          slug: "dlia-doma",
          is_active: 1,
          sale: null,
          sort: 6,
          created_at: "2024-06-01T17:39:52.000000Z",
        },
        {
          id: 7,
          title: "Аксессуары",
          slug: "aksessuary",
          is_active: 1,
          sale: null,
          sort: 7,
          created_at: "2024-06-01T17:39:52.000000Z",
        },
        {
          id: 8,
          title: "Подарки",
          slug: "podarki",
          is_active: 1,
          sale: null,
          sort: 8,
          created_at: "2024-06-01T17:39:52.000000Z",
        },
      ],

      collections: [
        { id: 1, title: "Teddy", slug: "/collections/teddy" },
        { id: 2, title: "Key", slug: "/collections/teddy" },
        { id: 3, title: "Tie", slug: "/collections/teddy" },
        { id: 4, title: "Waves", slug: "/collections/teddy" },
        { id: 5, title: "Trio", slug: "/collections/teddy" },
        { id: 6, title: "Classic", slug: "/collections/teddy" },
        { id: 7, title: "Bubbles", slug: "/collections/teddy" },
        { id: 8, title: "Royal", slug: "/collections/teddy" },
        { id: 9, title: "Le Lin", slug: "/collections/teddy" },
        { id: 10, title: "Geometry", slug: "/collections/teddy" },
        { id: 11, title: "Texture", slug: "/collections/teddy" },
        { id: 12, title: "Venice", slug: "/collections/teddy" },
        { id: 13, title: "Fleur", slug: "/collections/teddy" },
        { id: 14, title: "Italy", slug: "/collections/teddy" },
      ],
    },
    {
      id: 2,
      title: "Men",
      slug: "/men",
      links: [
        {
          id: 1,
          title: "Сумки",
          slug: "sumki",
          is_active: 1,
          sale: null,
          sort: 1,
          created_at: "2024-06-01T17:39:52.000000Z",
        },
        {
          id: 2,
          title: "Рюкзаки",
          slug: "riukzaki",
          is_active: 1,
          sale: null,
          sort: 2,
          created_at: "2024-06-01T17:39:52.000000Z",
        },
        {
          id: 3,
          title: "Ремни",
          slug: "remni",
          is_active: 1,
          sale: null,
          sort: 3,
          created_at: "2024-06-01T17:39:52.000000Z",
        },
        {
          id: 4,
          title: "Кошельки",
          slug: "koselki",
          is_active: 1,
          sale: null,
          sort: 4,
          created_at: "2024-06-01T17:39:52.000000Z",
        },
        {
          id: 5,
          title: "Косметички",
          slug: "kosmeticki",
          is_active: 1,
          sale: null,
          sort: 5,
          created_at: "2024-06-01T17:39:52.000000Z",
        },
        {
          id: 6,
          title: "Для дома",
          slug: "dlia-doma",
          is_active: 1,
          sale: null,
          sort: 6,
          created_at: "2024-06-01T17:39:52.000000Z",
        },
        {
          id: 7,
          title: "Аксессуары",
          slug: "aksessuary",
          is_active: 1,
          sale: null,
          sort: 7,
          created_at: "2024-06-01T17:39:52.000000Z",
        },
        {
          id: 8,
          title: "Подарки",
          slug: "podarki",
          is_active: 1,
          sale: null,
          sort: 8,
          created_at: "2024-06-01T17:39:52.000000Z",
        },
      ],
      collections: [
        { id: 1, title: "Teddy", slug: "/collections/teddy" },
        { id: 2, title: "Key", slug: "/collections/teddy" },
        { id: 3, title: "Tie", slug: "/collections/teddy" },
        { id: 4, title: "Waves", slug: "/collections/teddy" },
        { id: 5, title: "Trio", slug: "/collections/teddy" },
        { id: 6, title: "Classic", slug: "/collections/teddy" },
        { id: 7, title: "Bubbles", slug: "/collections/teddy" },
        { id: 8, title: "Royal", slug: "/collections/teddy" },
        { id: 9, title: "Le Lin", slug: "/collections/teddy" },
        { id: 10, title: "Geometry", slug: "/collections/teddy" },
        { id: 11, title: "Texture", slug: "/collections/teddy" },
        { id: 12, title: "Venice", slug: "/collections/teddy" },
        { id: 13, title: "Fleur", slug: "/collections/teddy" },
        { id: 14, title: "Italy", slug: "/collections/teddy" },
      ],
    },
    {
      id: 3,
      title: "New",
      slug: "/",
    },
    {
      id: 4,
      title: "Gifts",
      slug: "/",
    },
    {
      id: 5,
      title: "Sale",
      slug: "/",
    },
  ]);

  return { links };
});
